name: Update PR Status

on:
  pull_request:
    branches: [main]

jobs:
  update-pr-status:
    runs-on: ubuntu-latest

    steps:
      - name: Check Tests
        run: echo "Checking tests status"

      - name: Update PR status
        if: always()
        uses: actions/github-script@0.10.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: statuses } = await github.repos.listCommitStatusesForRef({
              ...context.repo,
              ref: context.sha,
            });

            const testsPassed = statuses.every((status) => status.state === 'success');

            if (testsPassed) {
              console.log('Tests passed. PR is ready to be merged.');
              process.exit(0);
            } else {
              console.log('Tests failed. PR cannot be merged.');
              process.exit(1);
            }
